# Generated by Django 4.0.3 on 2022-03-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction_expense_income_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='income',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
