# Generated by Django 4.0.3 on 2022-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('JOB', 'Job'), ('GIFT', 'Gift'), ('THEFT', 'Theft'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
    ]
